name: "Stefan Roi's portfolio"
favicon: null
layout_spectrum: 0.4755843817256391
typography_spectrum: 0.35899391304701567
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.021391152404248714
  lightness: 0.7323192346375436
  saturation: 0.5991118284873664
  rhythmicContrast: 0.6651042532175779
purpose: []
